### PR TITLE
Add option to pass size numOccurrences parameter to FromIntegerTypeConverter.getAppropriate(Volatile)Type

### PR DESCRIPTION
**Pull request by hanslovsky**
This is useful for creating multi-set types with different counts, e.g. for downsampled constant pixels.

### CODE REVIEW

**Comment by hanslovsky** [comment]
See https://github.com/saalfeldlab/paintera/commit/bf9353b59dfd322a1eaabcdcc368e2ccea41359e for an example use case

**Comment by igorpisarev** [comment]
@hanslovsky Would it make sense to deprecate or remove these methods `getAppropriateType()` and `getAppropriateVolatileType()` and just use the constructor directly? I think they used to have low-level initialization code, but a while ago it was moved into the constructors of `LabelMultisetType`.

**Comment by hanslovsky** [comment]
That would make sense but for convenience we should then probably add a constructor `LabelMultisetType( final int numOccurrences )` that would call `LabelMultisetType( LabelMultisetEntry )` and initialize the entry to `Label.INVALID`. What do you think?

**Comment by igorpisarev** [comment]
For `LabelMultisetType` I'm afraid that a constructor with a single `int` may give the wrong idea that it's the number of entries (and not the number of occurrences in a single entry). How about adding another constructor to the entry itself such as `LabelMultisetEntry(final int numOccurrences)`?

**Comment by hanslovsky** [comment]
Then maybe a static method in the `LabelMultisetType` could be useful, something like this:
```
LabelMultisetType.singleEntryWithOccurences
```
or similar.

**Comment by hanslovsky** [comment]
351cdd3 shows what it could look like. Naming is not necessarily final. What do you think about that?

**Comment by hanslovsky** [comment]
Thanks @igorpisarev I will go ahead and merge.

**Pull request merged**
